---
title: "Data management"
---

The analysis of your data is usually not the part of your project that takes longer : it is data wrangling. Your data have to be cleaned in order to be analyzed. This mean that you have a *tidy* datasets. Here we focus how we can combine and reshape different datasets in order to use them properly.

Maybe this session will be really focused on recoding data, work with the european social survey. 

## Dealing with NAs

```{r}
elec |> 
  map(is.na) |> 
  map(sum)

elec %>% 
        map(is.na) %>%
        map(sum)%>%
        map(~ . / nrow(df))%>%
        bind_cols()
library(naniar)

```

Working with surveys data, you will find a lot a `NA`. 

While we will not cover that here, be aware that there are also different imputations techniques that can be used. 


chaque ligne correspond à une observation chaque colonne correspond à une variable chaque valeur est présente dans une unique case de la table ou, de manière équivalente, des unités d'observations différentes sont présentes dans des tables différentes

-   Convert from raw form to tidy data
-   String processing, date parsing

## String processing : stringr package


## Date parsing : lubridate package
## Reshaping data

-   tidyr package

-   pivot_longer()

-   pivot_wider()

-   separate()

-   Complete, Fill \## Combining datasets

Most of the quantitative data projects involve not one datasets but many. Some original research might come by combining different datasets to analyze relationships we do not know about.

### Joins functions

-   left_join()
-   

### Binding functions

### Small introduction to web scraping

### String processing

### Date parsing
