project:
  type: book
  output-dir: docs
  execute-dir: file

book:
  title: "Introduction to R"
  author: "Malo Jan"
  date: "08/24/2023"
  search: true
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - part: "Session 1 : Getting started"
      chapters: 
        - session1/0101_whyr.qmd
        - session1/0102_setup.qmd
        - session1/0103_workflow.qmd
        - session1/0104_basics.qmd
        - session1/0105_import.qmd
        - session1/0106_help.qmd
        - session1/0107_exercise.qmd
    - part : "Session 2 : Manipulating data"
      chapters:
        - session2/0201_manipulate.qmd
        - session2/0202_reshape.qmd
        - session2/0203_exercise.qmd
    - part : "Session 3 : Data visualization"
      chapters:
        - session3/03_dataviz.qmd
        - session3/exo_3.qmd
    - part : "Session 4 : Testing relationships"
      chapters:
        - session4/04_relationships.qmd
    - part : "Session 5 : Correlation and regression"
      chapters:
        - session5/0501_correlation.qmd
        - session5/0502_regression.qmd
        - session5/exercice_5.qmd
    - part : "Session 6 : Multivariate analysis"
      chapters:
        - session6/06_modelling.qmd

  appendices: 
    - appendices/functions.qmd
    - appendices/ressources.qmd


bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    - style.css
    callout-appearance: simple
  pdf:
    documentclass: scrreprt

editor: visual

