project:
  type: book
  output-dir: docs
  execute-dir: file

book:
  title: "Introduction to R"
  author: "Malo Jan"
  date: "08/24/2023"
  search: true
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - part: "Session 1 : Getting started"
      chapters: 
        - session1/0101_whyr.qmd
        - session1/0102_setup.qmd
        - session1/0103_workflow.qmd
        - session1/0104_basics.qmd
        - session1/0105_import.qmd
        - session1/0106_help.qmd
    - part : "Session 2 : Manipulating data"
    - part : "Session 3 : Data visualization"
    - part : "Session 4 : Testing relationships"
    - part : "Session 5 : Cleaning data"
    - part : "Session 6 : Multivariate analysis"

  appendices: 
    - appendices/functions.qmd


bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    - style.css
    callout-appearance: simple
  pdf:
    documentclass: scrreprt

editor: visual

