---
title: "Introduction to R"
author: "Malo Jan"
---

## Your teacher

-   Malo Jan
-   Phd candidate in political science
-   Graduated from your master one year ago. 

My work focuses on political parties, parliament, political behavior and climate politics.
## The goals of this class

-   A "lab" session of the quantitative methods class (either taught by Jan Rovny or Jens Carstens)
-   Learn how to program with Rstudio
-   Teaching the basics and give you the willingness to learn more by yourself and in Quant 2

## Prerequisites

-   None

## Evaluation

-   Exercises
-   Group final exercice

# The motivation for this class

You might wonder, why bother and there are really different reasons for this.

## 

-   Automate

## What is programming useful for

-   Manipulate data, reshaping, descriptive statistics
-   Data vizualisation
-   Classical quantitative survey and experimental analysis

## Computational social science

-   Web scraping
-   Machine learning
-   Text, image and audio as data

## Programming and quantitative/qualitative research

-   Programming linked with quantitative research because
    -   Automation
    -   Statistical analysis
-   Collecting and archiving data
-   Transcribing data
